//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobetciEczane_IEO.IEOService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/", ConfigurationName="IEOService.nobetWebServiceSoap")]
    public interface nobetWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getIlceler", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getIlcelerResponse getIlceler(NobetciEczane_IEO.IEOService.getIlcelerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getIlceler", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getIlcelerResponse> getIlcelerAsync(NobetciEczane_IEO.IEOService.getIlcelerRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getEcz", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getEczResponse getEcz(NobetciEczane_IEO.IEOService.getEczRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getEcz", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getEczResponse> getEczAsync(NobetciEczane_IEO.IEOService.getEczRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobet", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getNobetResponse getNobet(NobetciEczane_IEO.IEOService.getNobetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobet", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetResponse> getNobetAsync(NobetciEczane_IEO.IEOService.getNobetRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetPR", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getNobetPRResponse getNobetPR(NobetciEczane_IEO.IEOService.getNobetPRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetPR", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetPRResponse> getNobetPRAsync(NobetciEczane_IEO.IEOService.getNobetPRRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetILS", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getNobetILSResponse getNobetILS(NobetciEczane_IEO.IEOService.getNobetILSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetILS", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetILSResponse> getNobetILSAsync(NobetciEczane_IEO.IEOService.getNobetILSRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://ws.ieo.org.tr/NobetWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetTEB", ReplyAction="*")]
        NobetciEczane_IEO.IEOService.getNobetTEBResponse getNobetTEB(NobetciEczane_IEO.IEOService.getNobetTEBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ieo.org.tr/NobetWebService/getNobetTEB", ReplyAction="*")]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetTEBResponse> getNobetTEBAsync(NobetciEczane_IEO.IEOService.getNobetTEBRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIlcelerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIlceler", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getIlcelerRequestBody Body;
        
        public getIlcelerRequest() {
        }
        
        public getIlcelerRequest(NobetciEczane_IEO.IEOService.getIlcelerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getIlcelerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        public getIlcelerRequestBody() {
        }
        
        public getIlcelerRequestBody(string userName, string userPass) {
            this.userName = userName;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIlcelerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIlcelerResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getIlcelerResponseBody Body;
        
        public getIlcelerResponse() {
        }
        
        public getIlcelerResponse(NobetciEczane_IEO.IEOService.getIlcelerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getIlcelerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getIlcelerResult;
        
        public getIlcelerResponseBody() {
        }
        
        public getIlcelerResponseBody(string getIlcelerResult) {
            this.getIlcelerResult = getIlcelerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEczRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEcz", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getEczRequestBody Body;
        
        public getEczRequest() {
        }
        
        public getEczRequest(NobetciEczane_IEO.IEOService.getEczRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getEczRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        public getEczRequestBody() {
        }
        
        public getEczRequestBody(string userName, string userPass) {
            this.userName = userName;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEczResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEczResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getEczResponseBody Body;
        
        public getEczResponse() {
        }
        
        public getEczResponse(NobetciEczane_IEO.IEOService.getEczResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getEczResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEczResult;
        
        public getEczResponseBody() {
        }
        
        public getEczResponseBody(string getEczResult) {
            this.getEczResult = getEczResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobet", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetRequestBody Body;
        
        public getNobetRequest() {
        }
        
        public getNobetRequest(NobetciEczane_IEO.IEOService.getNobetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string baslangicTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bitisTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ilceID;
        
        public getNobetRequestBody() {
        }
        
        public getNobetRequestBody(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            this.userName = userName;
            this.userPass = userPass;
            this.baslangicTarihi = baslangicTarihi;
            this.bitisTarihi = bitisTarihi;
            this.ilceID = ilceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetResponseBody Body;
        
        public getNobetResponse() {
        }
        
        public getNobetResponse(NobetciEczane_IEO.IEOService.getNobetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNobetResult;
        
        public getNobetResponseBody() {
        }
        
        public getNobetResponseBody(string getNobetResult) {
            this.getNobetResult = getNobetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetPRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetPR", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetPRRequestBody Body;
        
        public getNobetPRRequest() {
        }
        
        public getNobetPRRequest(NobetciEczane_IEO.IEOService.getNobetPRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetPRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string baslangicTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bitisTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ilceID;
        
        public getNobetPRRequestBody() {
        }
        
        public getNobetPRRequestBody(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            this.userName = userName;
            this.userPass = userPass;
            this.baslangicTarihi = baslangicTarihi;
            this.bitisTarihi = bitisTarihi;
            this.ilceID = ilceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetPRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetPRResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetPRResponseBody Body;
        
        public getNobetPRResponse() {
        }
        
        public getNobetPRResponse(NobetciEczane_IEO.IEOService.getNobetPRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetPRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNobetPRResult;
        
        public getNobetPRResponseBody() {
        }
        
        public getNobetPRResponseBody(string getNobetPRResult) {
            this.getNobetPRResult = getNobetPRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetILSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetILS", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetILSRequestBody Body;
        
        public getNobetILSRequest() {
        }
        
        public getNobetILSRequest(NobetciEczane_IEO.IEOService.getNobetILSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetILSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string baslangicTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bitisTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ilceID;
        
        public getNobetILSRequestBody() {
        }
        
        public getNobetILSRequestBody(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            this.userName = userName;
            this.userPass = userPass;
            this.baslangicTarihi = baslangicTarihi;
            this.bitisTarihi = bitisTarihi;
            this.ilceID = ilceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetILSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetILSResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetILSResponseBody Body;
        
        public getNobetILSResponse() {
        }
        
        public getNobetILSResponse(NobetciEczane_IEO.IEOService.getNobetILSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetILSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNobetILSResult;
        
        public getNobetILSResponseBody() {
        }
        
        public getNobetILSResponseBody(string getNobetILSResult) {
            this.getNobetILSResult = getNobetILSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetTEBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetTEB", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetTEBRequestBody Body;
        
        public getNobetTEBRequest() {
        }
        
        public getNobetTEBRequest(NobetciEczane_IEO.IEOService.getNobetTEBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetTEBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string baslangicTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bitisTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ilceID;
        
        public getNobetTEBRequestBody() {
        }
        
        public getNobetTEBRequestBody(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            this.userName = userName;
            this.userPass = userPass;
            this.baslangicTarihi = baslangicTarihi;
            this.bitisTarihi = bitisTarihi;
            this.ilceID = ilceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNobetTEBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNobetTEBResponse", Namespace="http://ws.ieo.org.tr/NobetWebService/", Order=0)]
        public NobetciEczane_IEO.IEOService.getNobetTEBResponseBody Body;
        
        public getNobetTEBResponse() {
        }
        
        public getNobetTEBResponse(NobetciEczane_IEO.IEOService.getNobetTEBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.ieo.org.tr/NobetWebService/")]
    public partial class getNobetTEBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNobetTEBResult;
        
        public getNobetTEBResponseBody() {
        }
        
        public getNobetTEBResponseBody(string getNobetTEBResult) {
            this.getNobetTEBResult = getNobetTEBResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface nobetWebServiceSoapChannel : NobetciEczane_IEO.IEOService.nobetWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class nobetWebServiceSoapClient : System.ServiceModel.ClientBase<NobetciEczane_IEO.IEOService.nobetWebServiceSoap>, NobetciEczane_IEO.IEOService.nobetWebServiceSoap {
        
        public nobetWebServiceSoapClient() {
        }
        
        public nobetWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public nobetWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nobetWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nobetWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getIlcelerResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getIlceler(NobetciEczane_IEO.IEOService.getIlcelerRequest request) {
            return base.Channel.getIlceler(request);
        }
        
        public string getIlceler(string userName, string userPass) {
            NobetciEczane_IEO.IEOService.getIlcelerRequest inValue = new NobetciEczane_IEO.IEOService.getIlcelerRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getIlcelerRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            NobetciEczane_IEO.IEOService.getIlcelerResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getIlceler(inValue);
            return retVal.Body.getIlcelerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getIlcelerResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getIlcelerAsync(NobetciEczane_IEO.IEOService.getIlcelerRequest request) {
            return base.Channel.getIlcelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getIlcelerResponse> getIlcelerAsync(string userName, string userPass) {
            NobetciEczane_IEO.IEOService.getIlcelerRequest inValue = new NobetciEczane_IEO.IEOService.getIlcelerRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getIlcelerRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getIlcelerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getEczResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getEcz(NobetciEczane_IEO.IEOService.getEczRequest request) {
            return base.Channel.getEcz(request);
        }
        
        public string getEcz(string userName, string userPass) {
            NobetciEczane_IEO.IEOService.getEczRequest inValue = new NobetciEczane_IEO.IEOService.getEczRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getEczRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            NobetciEczane_IEO.IEOService.getEczResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getEcz(inValue);
            return retVal.Body.getEczResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getEczResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getEczAsync(NobetciEczane_IEO.IEOService.getEczRequest request) {
            return base.Channel.getEczAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getEczResponse> getEczAsync(string userName, string userPass) {
            NobetciEczane_IEO.IEOService.getEczRequest inValue = new NobetciEczane_IEO.IEOService.getEczRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getEczRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getEczAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getNobetResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobet(NobetciEczane_IEO.IEOService.getNobetRequest request) {
            return base.Channel.getNobet(request);
        }
        
        public string getNobet(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetRequest inValue = new NobetciEczane_IEO.IEOService.getNobetRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            NobetciEczane_IEO.IEOService.getNobetResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobet(inValue);
            return retVal.Body.getNobetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetAsync(NobetciEczane_IEO.IEOService.getNobetRequest request) {
            return base.Channel.getNobetAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetResponse> getNobetAsync(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetRequest inValue = new NobetciEczane_IEO.IEOService.getNobetRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getNobetPRResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetPR(NobetciEczane_IEO.IEOService.getNobetPRRequest request) {
            return base.Channel.getNobetPR(request);
        }
        
        public string getNobetPR(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetPRRequest inValue = new NobetciEczane_IEO.IEOService.getNobetPRRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetPRRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            NobetciEczane_IEO.IEOService.getNobetPRResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetPR(inValue);
            return retVal.Body.getNobetPRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetPRResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetPRAsync(NobetciEczane_IEO.IEOService.getNobetPRRequest request) {
            return base.Channel.getNobetPRAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetPRResponse> getNobetPRAsync(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetPRRequest inValue = new NobetciEczane_IEO.IEOService.getNobetPRRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetPRRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetPRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getNobetILSResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetILS(NobetciEczane_IEO.IEOService.getNobetILSRequest request) {
            return base.Channel.getNobetILS(request);
        }
        
        public string getNobetILS(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetILSRequest inValue = new NobetciEczane_IEO.IEOService.getNobetILSRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetILSRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            NobetciEczane_IEO.IEOService.getNobetILSResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetILS(inValue);
            return retVal.Body.getNobetILSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetILSResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetILSAsync(NobetciEczane_IEO.IEOService.getNobetILSRequest request) {
            return base.Channel.getNobetILSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetILSResponse> getNobetILSAsync(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetILSRequest inValue = new NobetciEczane_IEO.IEOService.getNobetILSRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetILSRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetILSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NobetciEczane_IEO.IEOService.getNobetTEBResponse NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetTEB(NobetciEczane_IEO.IEOService.getNobetTEBRequest request) {
            return base.Channel.getNobetTEB(request);
        }
        
        public string getNobetTEB(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetTEBRequest inValue = new NobetciEczane_IEO.IEOService.getNobetTEBRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetTEBRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            NobetciEczane_IEO.IEOService.getNobetTEBResponse retVal = ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetTEB(inValue);
            return retVal.Body.getNobetTEBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetTEBResponse> NobetciEczane_IEO.IEOService.nobetWebServiceSoap.getNobetTEBAsync(NobetciEczane_IEO.IEOService.getNobetTEBRequest request) {
            return base.Channel.getNobetTEBAsync(request);
        }
        
        public System.Threading.Tasks.Task<NobetciEczane_IEO.IEOService.getNobetTEBResponse> getNobetTEBAsync(string userName, string userPass, string baslangicTarihi, string bitisTarihi, int ilceID) {
            NobetciEczane_IEO.IEOService.getNobetTEBRequest inValue = new NobetciEczane_IEO.IEOService.getNobetTEBRequest();
            inValue.Body = new NobetciEczane_IEO.IEOService.getNobetTEBRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPass = userPass;
            inValue.Body.baslangicTarihi = baslangicTarihi;
            inValue.Body.bitisTarihi = bitisTarihi;
            inValue.Body.ilceID = ilceID;
            return ((NobetciEczane_IEO.IEOService.nobetWebServiceSoap)(this)).getNobetTEBAsync(inValue);
        }
    }
}
